---
# task for haproxy
- name: Install haproxy
  apt:
    state: present
    pkg:
      - haproxy
  tags: haproxy

- name: Generate configuration
  copy:
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Restart haproxy 
  tags: haproxy

- name: Allow port 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT
  when: iptables_enable | default(True)
  tags: haproxy

- name: Allow port 443
  iptables:
    chain: INPUT
    protocol: tcp
    destionation_port: "443"
    jump: ACCEPT
  when: iptables_enable | default(True)
  tags: haproxy
