---
- name: Deploy grafana docker container
  docker_container:
    state: started
    restart_policy: always
    name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  tags: grafana

- name: Check if defined password is working
  uri:
    url: http://grafana.proxima.bentouati.net/api/users
    user: admin
    password: "{{ grafana_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200,401
  register: grafana_check_password
  until: grafana_check_password.status != -1
  ignore_errors: yes
  tags: grafana

- name: Change password
  uri:
    url: http://grafana.proxima.bentouati.net/api/user/password
    user: admin
    password: "{{ grafana_default_password }}"
    method: PUT
    body: '{"oldPassword": "{{ grafana_default_password }}", "newPassword": "{{ grafana_password }}", "confirmNew": "{{ grafana_password }}"}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
  when: grafana_check_password.status == 401
  ignore_errors: yes
  tags: grafana

- name: Check prometheus datasource presence
  uri:
    url: http://grafana.proxima.bentouati.net/api/datasources/name/prometheus
    user: admin
    password: "{{ grafana_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200,404
  register: grafana_check_datasource 
  tags: grafana

- name: Add prometheus datasource
  uri:
    url: http://grafana.proxima.bentouati.net/api/datasources
    user: admin
    password: "{{ grafana_password }}"
    method: POST
    body: '{"name":"prometheus", "type":"prometheus", "url":"http://prometheus.proxima.bentouati.net", "access":"proxy", "basicAuth":true, "basicAuthUser": "admin", "secureJsonData":{"basicAuthPassword":"{{ grafana_password }}"}}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
  when: grafana_check_datasource.status == 404
  tags: grafana
