---
- name: Create /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    mode: 0755
  tags: prometheus

- name: Generate conf
  template:
    src: "{{item.local}}"
    dest: "{{item.remote}}"
  loop:
    - {local: "prometheus.yml", remote: "/etc/prometheus/prometheus.yml"}
    - {local: "web.yml", remote: "/etc/prometheus/web.yml"}
  notify: Reload prometheus
  tags: prometheus

- name: Deploy prometheus container
  docker_container:
    state: started
    restart_policy: always
    name: prometheus
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
      - /etc/prometheus:/etc/prometheus
    command: >-
              --config.file=/etc/prometheus/prometheus.yml --web.config.file=/etc/prometheus/web.yml
  register: prom_container_result
  tags: prometheus
