---
# task for common

- name: Update & upgrade
  apt:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: common

- name: Install packages
  apt:
    state: present
    pkg:
      -
      - git
      - python3
      - python3-pip
      - htop
      - vim
      - wget
      - curl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: common
