---
# Tasks for docker

- name: Install prerequisites
  apt:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-docker
  tags: docker

- name: Add repos keys
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags: docker

- name: Add source list
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release  }} stable"
    state: present
  tags: docker

- name: Install docker
  apt:
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags: docker
