---
- name: Create /etc/sourcegraph
  file:
    path: /etc/sourcegraph
    state: directory
    mode: 0755
  tags: sourcegraph

- name: Create /var/opt/sourcegraph
  file:
    path: /var/opt/sourcegraph
    state: directory
    mode: 0755
  tags: sourcegraph

- name: Deploy sourcegraph container
  docker_container:
    state: started
    restart_policy: always
    name: sourcegraph
    image: sourcegraph/server
    network_mode: host
    volumes:
      - /etc/sourcegraph:/etc/sourcegraph
      - /var/opt/sourcegraph:/var/opt/sourcegraph
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7080:7080"
